external_profile_url:
  type: string
  default: ""
  description: "The base url for the external link user input field. For example, 'http://github.com/'."
external_profile_label:
  type: string
  default: ""
  description: "The name that will be used to display the link. For example, 'GitHub'."
external_user_field:
  type: string
  default: ""
  description: "The exact name of the custom user input field. For example, 'Github username'."
